### PR TITLE
WIP Fix/277

### LINKED ISSUE #277: Correct time from  token
See https://openid.net/specs/openid-connect-core-1_0.html#IDToken  
## Details 
- exp
REQUIRED. Expiration time on or after which the ID Token MUST NOT be accepted for processing. The processing of this parameter requires that the current date/time MUST be before the expiration date/time listed in the value. Implementers MAY provide for some small leeway, usually no more than a few minutes, to account for clock skew. Its value is a JSON number representing the number of seconds from 1970-01-01T0:0:0Z as measured in UTC until the date/time. See RFC 3339 [RFC3339] for details regarding date/times in general and UTC in particular.

- auth_time
Time when the End-User authentication occurred. Its value is a JSON number representing the number of seconds from 1970-01-01T0:0:0Z as measured in UTC until the date/time. When a max_age request is made or when auth_time is requested as an Essential Claim, then this Claim is REQUIRED; otherwise, its inclusion is OPTIONAL. (The auth_time Claim semantically corresponds to the OpenID 2.0 PAPE [OpenID.PAPE] auth_time response parameter.)

## Issues
- Adding current time and the value of the expires in will result in an expires in that will be way after the actual expires in value.  
- Authentication time isn't when you got the token.  It is when the user authenticated.  This is not currently exposed in https://github.com/IdentityModel/IdentityModel/blob/main/src/Client/Messages/TokenResponse.cs but should be.

### PR DESCRIPTION
**Pull request by vbjay**
fixes #277 

- Gets the authentication time from the token instead of now, if possible.  If not possible, then return nulll DateTimeOffset?.  
- Make RefreshTokenResult also use DateTimeOffset

### CODE REVIEW

File: src/OidcClient/OidcClient.cs [hunk 1]
```diff
@@ -229,14 +232,20 @@ public virtual async Task<LoginResult> ProcessResponseAsync(string data, Authori
 
             var user = ProcessClaims(result.User, userInfoClaims);
 
+            long seconds = 0;
+            var authTimeValue = result.TokenResponse.TryGet(JwtClaimTypes.AuthenticationTime);
+            DateTimeOffset? authTime = null;
+            if (authTimeValue.IsPresent() && long.TryParse(authTimeValue, out seconds))
+                authTime = new DateTimeOffset(TOKEN_START_TIME, TimeSpan.Zero).AddSeconds(seconds);
```
Comment (leastprivilege) [inline src/OidcClient/OidcClient.cs:239]: I would use the ´FromUnixTimeSeconds´ methods instead.

Comment (vbjay) [reply src/OidcClient/OidcClient.cs:239]: I wanted to be exact based on the spec. But unix time does use the same value so not a problem.

Comment (leastprivilege) [reply src/OidcClient/OidcClient.cs:239]: want to update your PR?

Comment (leastprivilege) [reply src/OidcClient/OidcClient.cs:239]: I'll add it myself. Got time today.

**Comment by vbjay** [comment]
Thanks. Was swamped with getting phase 2 of Blue Rhino home delivery
deployed.
